baseURL: https://www.jonahramponi.com
languageCode: en-us
title: Jonah's ML Notes
theme: PaperMod
# theme: Archie
pygmentsstyle: "monokai"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
paginate: 3

params:
  # mode: "toggle" 
  math: true
  mathjax: true 
  katex: true 

menu:
  main:
   - name: "Home"
     url: "/"
     weight: 1

   - name: "About"
     url: "/about"
     weight: 3

disableKinds:
  - "404"

custom_css:
  - "css/custom.css"

favicon: "/assets/favicon.ico"